// GENERATED by scripts/build-sw.mjs from scripts/sw-template.js — do not edit by hand.
// Run `npm run build:sw` after changing any app file or question file.
const VERSION = 'c089bc53d625';
const CACHE = 'quizcert-' + VERSION;
const PRECACHE = [
  ".",
  "index.html",
  "style.css",
  "manifest.webmanifest",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "src/data-loader.js",
  "src/engine.js",
  "src/i18n.js",
  "src/main.js",
  "src/schema.js",
  "src/select.js",
  "src/session.js",
  "src/stats.js",
  "src/storage.js",
  "src/ui.js",
  "data/manifest.json",
  "data/questions/cor-az500.json",
  "data/questions/cor-cyberops.json",
  "data/questions/cor-cysa.json",
  "data/questions/cor-iso27001.json",
  "data/questions/cor-lpic.json",
  "data/questions/cor-ms102.json",
  "data/questions/cor-pentest.json",
  "data/questions/cor-sc300.json",
  "data/questions/hv-darkweb-vpn.json",
  "data/questions/mix-ad.json",
  "data/questions/mix-backup.json",
  "data/questions/mix-cloud.json",
  "data/questions/mix-db.json",
  "data/questions/mix-hardware.json",
  "data/questions/mix-itops.json",
  "data/questions/mix-linux.json",
  "data/questions/mix-oswin.json",
  "data/questions/mix-scripting.json",
  "data/questions/mix-virt.json",
  "data/questions/o1-ccna.json",
  "data/questions/o1-crypto.json",
  "data/questions/o1-forense.json",
  "data/questions/o1-fortinet.json",
  "data/questions/o1-google.json",
  "data/questions/o1-ibm.json",
  "data/questions/o1-microsoft.json",
  "data/questions/o1-paloalto.json",
  "data/questions/o1b-gcloud.json",
  "data/questions/o1b-glossario.json",
  "data/questions/o1b-googleai.json",
  "data/questions/o1b-netdef.json",
  "data/questions/o1b-nmapwire.json",
  "data/questions/o1b-tooling.json",
  "data/questions/o1b-websec.json",
  "data/questions/o2-az900.json",
  "data/questions/o2-ceh.json",
  "data/questions/o2-itil4.json",
  "data/questions/o2-md102.json",
  "data/questions/o2-networkplus.json",
  "data/questions/o2-nse5.json",
  "data/questions/o2-nse6.json",
  "data/questions/o2-nse7.json",
  "data/questions/o2-securityplus.json",
  "data/questions/o3-az900.json",
  "data/questions/o3-ccna.json",
  "data/questions/o3-ceh.json",
  "data/questions/o3-crypto.json",
  "data/questions/o3-forense.json",
  "data/questions/o3-fortinet.json",
  "data/questions/o3-gcloud.json",
  "data/questions/o3-glossario.json",
  "data/questions/o3-google.json",
  "data/questions/o3-googleai.json",
  "data/questions/o3-ibm.json",
  "data/questions/o3-itil4.json",
  "data/questions/o3-md102.json",
  "data/questions/o3-microsoft.json",
  "data/questions/o3-netdef.json",
  "data/questions/o3-networkplus.json",
  "data/questions/o3-nmapwire.json",
  "data/questions/o3-nse5.json",
  "data/questions/o3-nse6.json",
  "data/questions/o3-nse7.json",
  "data/questions/o3-paloalto.json",
  "data/questions/o3-securityplus.json",
  "data/questions/o3-tooling.json",
  "data/questions/o3-websec.json",
  "data/questions/o4-az900.json",
  "data/questions/o4-ccna.json",
  "data/questions/o4-ceh.json",
  "data/questions/o4-fortinet.json",
  "data/questions/o4-google.json",
  "data/questions/o4-ibm.json",
  "data/questions/o4-itil4.json",
  "data/questions/o4-md102.json",
  "data/questions/o4-networkplus.json",
  "data/questions/o4-paloalto.json",
  "data/questions/o4-sc900.json",
  "data/questions/o4-securityplus.json",
  "data/questions/o5-ad.json",
  "data/questions/o5-az500.json",
  "data/questions/o5-backup.json",
  "data/questions/o5-cloud.json",
  "data/questions/o5-cyberops.json",
  "data/questions/o5-cysa.json",
  "data/questions/o5-darkweb.json",
  "data/questions/o5-db.json",
  "data/questions/o5-googleai.json",
  "data/questions/o5-hardware.json",
  "data/questions/o5-iso27001.json",
  "data/questions/o5-itops.json",
  "data/questions/o5-linux.json",
  "data/questions/o5-lpic.json",
  "data/questions/o5-ms102.json",
  "data/questions/o5-oswin.json",
  "data/questions/o5-pentest.json",
  "data/questions/o5-sc300.json",
  "data/questions/o5-scripting.json",
  "data/questions/o5-tooling.json",
  "data/questions/o5-virt.json",
  "data/questions/sample.json"
];

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // cache: 'reload' bypasses the HTTP cache, so a fresh deploy is never
    // frozen into the new offline cache with stale copies of the files.
    await cache.addAll(PRECACHE.map((url) => new Request(url, { cache: 'reload' })));
    // Old hand-versioned workers (quizcert-vN) run a page without the update
    // prompt: replace them right away instead of waiting for every tab to close.
    const keys = await caches.keys();
    if (keys.some((k) => /^quizcert-v\d+$/.test(k))) await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k.startsWith('quizcert-') && k !== CACHE).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

// The page asks for activation when the user clicks "Update".
self.addEventListener('message', (event) => {
  if (event.data === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const isNav = req.mode === 'navigate';
    const hit = await cache.match(req, { ignoreSearch: isNav });
    if (hit) return hit;
    try {
      return await fetch(req);
    } catch (err) {
      if (isNav) {
        const shell = await cache.match('index.html');
        if (shell) return shell;
      }
      throw err;
    }
  })());
});
